/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package assignment1;

import java.util.Scanner;

/**
 * This is the App.
 */
public class App {

  /**
   * The App starting point.
   *
   * @param args Unused program arguments.
   */
  public static void main(String[] args) {
    try {
      // Present the menu.
      Scanner scan = new Scanner(System.in, "utf-8");
      /* 
      Menu theMenu = new Menu();
      theMenu.start(scan);*/
      HashTests tests = new HashTests();
      tests.printUniformityTestArray();
      scan.close();
    } catch (Exception e) {
      System.out.println("Exception: " + e.getMessage());
      e.printStackTrace();
    } catch (Error error) {
      System.out.println("Error: " + error.getMessage());
      error.printStackTrace();
    }
  }
}
